[production]
stfc-demo ansible_host=VM_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-key.pem

[production:vars]
ansible_python_interpreter=/usr/bin/python3

[staging]

[all:vars]
app_name=tellmewhen
app_user=tellmewhen
app_dir=/opt/tellmewhen
container_dir={{ app_dir }}/containers
data_dir={{ app_dir }}/data